Refactor of smarthome application
SniXosha/smart-home-2019 pull request #1
Opened 2019-10-15 16:05 UTC by SniXosha

2019-10-16 20:12 UTC, iagoshkov requested changes
Исправьте по замечаниям.
Основное - абстракции Device и ComplexTrigger получились плохие.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
>  public class HomeBuilder {
У вас в этом классе смешано куча responsibility:
1) загрузка дома из json
2) конструирование тестового дома
3) настройка ComplexTrigger-ов
4) сохранение дома
Это все нарушение SRP.
Исправляйте.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/HomeRunner.java
> +
Нарушен SRP.
У вас в этом классе две обязанности - цикл обработки событий + генерация случайных событий.
Вообще для генерации событий нужно сделать абстракцию - сейчас мы случайным образом генерируем их, просто для теста. А в будущем подключим реальную библиотеку - придется здесь переписывать код.
Исправьте.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void processEvent(SensorEvent event) {
Почему вы часть событий обрабатываете в самих Device - а часть в ComplexTrigger?
Сделайте одну хорошую абстракцию, а не две разные.
Почему ComplexTrigger - он же ничего не "триггерит", а наоборот обрабатывает события.
Исправьте.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void processEvent(SensorEvent event) {
И вообще обработка событий от внешних устройств является ли обязанностью дома?
Это нарушение SRP.
Тоже исправьте.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/TurnOffAllLights.java
> +    public void processEvent(SensorEvent event) {
Этот метод очень сложно читать. Если у вас он останется после рефакторинга по замечаниям выше - примените внутри него extractMethod рефакторинг, чтобы его было проще читать.

2019-10-16 20:12 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +class DeviceDeserializer<T extends Device> implements JsonDeserializer<T> {
Излишнее усложнение, в котором нет необходимости.
Весь рефакторинг можно проделать без изменения структуры хранения дома в json и без необходимости реализовывать свои JsonDeserializer-ы.

2019-10-17 14:49 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +class DeviceDeserializer<T extends Device> implements JsonDeserializer<T> {
Можно, но поля doors, lights выглядят слишком хардкодно, поэтому думаю можно оставить

2019-10-17 14:50 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
>  public class HomeBuilder {
Оставил только сохранение и зарузку статического дома

2019-10-17 14:51 UTC, SniXosha commented
Исправил основные замечания.

2019-10-22 22:11 UTC, a-ivanov requested changes
В целом уже хорошо, немного доработать детали.

2019-10-22 22:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
>  public class HomeBuilder {
Если оставляете, то добавьте интерфейс для абстракции по чтению состояния дома.

2019-10-22 22:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/EventProcessor.java
> +    void setSmartHome(SmartHome smartHome);
Зачем выносить сеттер в API, когда SmartHome можно передавать в конструктор имплементации EventProcessor на этапе ее создания? Сейчас любой пользователь EventProcessor может подменить дом и такой баг будет потом тяжело найти - наш исходный дом не будет обновляться.

2019-10-22 22:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +class DeviceDeserializer<T extends Device> implements JsonDeserializer<T> {
Почему хардкодно, если Room как сущность (по определению) состоит из коллекции Door и коллекции Light? Это как раз более понятно в сравнении с десериализацией (которая нужна для другого). Надо проще и ближе к предметной области.

2019-10-23 16:56 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +class DeviceDeserializer<T extends Device> implements JsonDeserializer<T> {
У нас изначально есть smarthome. И сейчас хардкодиться, что из девайсов там будут только двери и лампочки, не хочется. Ведь в умном доме какие-угодно могут быть предметы

2019-10-23 20:11 UTC, a-ivanov requested changes
Так гораздо лучше. После правки leaky abstraction - с моей стороны зачет.

2019-10-23 20:11 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/HomeBuilder.java
> +    SmartHome loadSmartHome() throws IOException;
Leaky abstraction: детали имплементации в интерфейсе (абстракции). Исправьте.

2019-10-23 20:44 UTC, a-ivanov approved these changes

2019-11-07 12:15 UTC, merged