Hometask 3
SniXosha/smart-home-2019 pull request #3
Opened 2019-10-24 22:08 UTC by SniXosha

Added new alarm object

2019-10-30 11:54 UTC, a-ivanov requested changes

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedAlarm.java
> +        if (code.equals(this.code)) {
IMHO: Проверка кода - это еще одна responsibility, и мы можем захотеть поменять ее (например, сменить алгоритм расшифровки). Можно выносить смело в отдельную абстракцию, например java.util.function.Predicate.

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedDangerAlarm.java
> +    public void activateDangerAlarm() {
Здесь сигнализация переходит в режим "опасности"?

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +    public void activateDangerAlarm() {
Здесь сигнализация переходит в режим "опасности"?

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    void processEvent(Object event);
А зачем тут исчез SensorEvent? Ведь в нем есть информация по типу события и не нужно в имплементациях кастовать, чтобы узнавать тип события. На мой взгляд, надо вернуть, как было.

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    boolean isCorrectEvent(Object event);
Тогда вот такие дополнительные методы в интерфейсе будут не нужны. Сейчас `isCorrectEvent` - leaky abstraction (это деталь проверки, может быть имплементация будет обрабатывать событие без проверки).

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/TriggerAlarm.java
> +        this.homeAlarm = homeAlarm;
Alarm - тоже Actionable, пользуйтесь этим интерфейсом, не надо ее отдельно запрашивать. Исправьте.

2019-10-30 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/sensorevents/EventDispatcher.java
> +    public static Object getNextSensorEvent() {
Должен возвращать SensorEvent.

2019-10-31 13:30 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedAlarm.java
> +        if (code.equals(this.code)) {
По-моему это перебор. Зачем сейчас что-то усложнять без надобности?

2019-10-31 13:31 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedDangerAlarm.java
> +    public void activateDangerAlarm() {
Здесь она уже в состоянии "опасности", поэтому ничего не просходит

2019-10-31 13:32 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +    public void activateDangerAlarm() {
В данном случае работает так, что сначала сигнализацию нужно активировать

2019-10-31 13:33 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    void processEvent(Object event);
SensorEvent может быть каким-угодно и общих деталей у них не наблюдается. Поэтому принимается просто Object, а дальше процессор с помощью instanceof сам выбирает с какими событиями работает. 
Можно конечно добавить пустой интерфейс

2019-10-31 13:36 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    boolean isCorrectEvent(Object event);
Это сделано с другой целью. Мы должны понимать триггерится ли процессор на поступающий event, чтобы только в этом случае активировать сигнализацию

2019-10-31 13:39 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/TriggerAlarm.java
> +        this.homeAlarm = homeAlarm;
Непонятно зачем. Нам ведь нужен Alarm, а не какой то Actionable

2019-10-31 13:39 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/sensorevents/EventDispatcher.java
> +    public static Object getNextSensorEvent() {
Ответил выше

2019-10-31 14:40 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +    public void activateDangerAlarm() {
В домашке имелось в виду, что это принудительной перевод (такая "тревожная кнопка") в состояние Alarm.
Поэтому тут можно добавить переход в ActivatedDangerState.

2019-10-31 14:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    boolean isCorrectEvent(Object event);
В домашке написано, что если сигнализация находится в состоянии "активирована", то любое событие от сенсоров должно переводить ее в режим тревоги - неважно есть на эти события eventProcessor-ы, которые собираются их обрабатывать или нет.
Поэтому это условие можно убрать из декоратора и убрать из интерфейса.

2019-10-31 14:53 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/TriggerAlarm.java
> +        this.homeAlarm = homeAlarm;
Замечание снято.

2019-10-31 14:55 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/sensorevents/EventDispatcher.java
> +    public static Object getNextSensorEvent() {
ок

2019-10-31 14:58 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedAlarm.java
> +        if (code.equals(this.code)) {
Да, ок, можно оставить так.

2019-10-31 14:59 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/ActivatedDangerAlarm.java
> +    public void activateDangerAlarm() {
ок

2019-10-31 14:59 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    void processEvent(Object event);
ок

2019-10-31 15:11 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/eventprocessors/EventProcessor.java
> +    boolean isCorrectEvent(Object event);
Тогда получается декораторы нужны не на отдельные процессоры, а ещё выше?

2019-11-04 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +        if (code.equals(this.code)) {
В этом состоянии задается изначальный код, его еще не с чем сверять (тут типа как сейф в отеле).

2019-11-05 09:30 UTC, SniXosha commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +        if (code.equals(this.code)) {
Тогда как деактивировать тревогу? Плюс в ТЗ же такого не было. Это критично для выполнения дальнейших заданий?

2019-11-05 10:42 UTC, sbt-agoshkov commented
Не, не критично.Можно какой нить "дефолтный" вшитый пароль наверно и оставить для таких случаев.12:30, 5 ноября 2019 г., SniXosha <notifications@github.com>:@SniXosha commented on this pull request.



In src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java:
> @@ -0,0 +1,27 @@
+package ru.sbt.mipt.oop.smarthome.alarm;
+
+public class DeactivatedAlarm extends HomeAlarmState {
+
+    private final String code;
+
+    DeactivatedAlarm(HomeAlarm homeAlarm, String code) {
+        this.code = code;
+        this.homeAlarm = homeAlarm;
+    }
+
+    @Override
+    public void activate(String code) {
+        if (code.equals(this.code)) {

Тогда как деактивировать тревогу? Плюс в ТЗ же такого не было. Это критично для выполнения дальнейших заданий?

—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or unsubscribe.
Илья

2019-11-07 09:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/DeactivatedAlarm.java
> +        if (code.equals(this.code)) {
Ну желательно)

2019-11-07 09:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/HomeAlarmState.java
> +public abstract class HomeAlarmState implements Alarm {
IMHO: зачем делать абстрактный класс? Интерфейсы могут расширять другие интерфейсы.

2019-11-07 09:49 UTC, a-ivanov approved these changes

2019-11-07 12:15 UTC, merged